storeEmployee: storeEmployee_main.o storeEmployee.o 
	g++ -o storeEmployee storeEmployee_main.o storeEmployee.o 
 
storeEmployee_main.o: storeEmployee_main.cpp storeEmployee.h 
	g++ -c storeEmployee_main.cpp 
 
storeEmployee.o: storeEmployee.cpp storeEmployee.h 
	g++ -c storeEmployee.cpp